# Generated by Django 4.2.20 on 2025-05-11 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activityui', '0004_alter_activity_options_activity_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='arrival',
            field=models.CharField(default='AAAA', max_length=4, verbose_name='目的'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='departure',
            field=models.CharField(default='AAAA', max_length=4, verbose_name='始发'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='活动时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='capacity',
            field=models.IntegerField(default=999, verbose_name='活动容量'),
        ),
    ]
