# Generated by Django 4.2.20 on 2025-05-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityui', '0005_activity_arrival_activity_departure_activity_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='aircraft',
            field=models.TextField(default='A20N', max_length=255, verbose_name='机型'),
            preserve_default=False,
        ),
    ]
