# Generated by Django 4.2.20 on 2025-05-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityui', '0006_registration_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='flt_nbr',
            field=models.TextField(default='MF0000', max_length=8, verbose_name='航班号'),
            preserve_default=False,
        ),
    ]
