# Generated by Django 4.2.20 on 2025-05-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityui', '0008_atcregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='atcregistration',
            name='seat',
            field=models.CharField(default='TWR', max_length=16, verbose_name='席位'),
            preserve_default=False,
        ),
    ]
