# Generated by Django 4.2.20 on 2025-05-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityui', '0009_atcregistration_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='结束时间'),
        ),
    ]
