# Generated by Django 4.2.20 on 2025-05-17 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activityui', '0010_activity_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATCPermissionGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('DEL', '放行'), ('GND', '地面'), ('TWR', '塔台'), ('APP', '进近'), ('CTR', '区调')], max_length=3, verbose_name='席位')),
                ('permission', models.CharField(choices=[('NO', '无权限'), ('TRN', '实习中'), ('RLD', '已放单')], default='NO', max_length=3, verbose_name='权限级别')),
                ('granted_time', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='最后修改')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '管制权限',
                'verbose_name_plural': '管制权限',
                'unique_together': {('user', 'position')},
            },
        ),
    ]
