# Generated by Django 4.2.20 on 2025-05-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityui', '0011_atcpermissiongrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcpermissiongrant',
            name='permission',
            field=models.CharField(choices=[('TRN', '实习中'), ('RLD', '已放单')], default='TRN', max_length=3, verbose_name='权限级别'),
        ),
    ]
