# Generated by Django 4.2.20 on 2025-05-18 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activityui', '0013_alter_atcpermissiongrant_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcpermissiongrant',
            name='position',
            field=models.CharField(choices=[('DEL', '放行'), ('GND', '地面'), ('TWR', '塔台'), ('APP', '进近'), ('CTR', '区调'), ('FIS', '飞服'), ('PTW', '程序塔台'), ('APN', '机坪')], max_length=3, verbose_name='席位'),
        ),
        migrations.AlterUniqueTogether(
            name='atcregistration',
            unique_together={('user', 'activity'), ('activity', 'seat')},
        ),
    ]
